language: php
sudo: enabled

services:
  - mysql

addons:
  chrome: stable

git:
  depth: 3

php:
  - '5.6'
  - '7.0'
  - '7.1'
  - '7.2'

env:
  global:
    - HUMHUB_PATH=/opt/humhub
  matrix:
    - HUMHUB_VERSION=master
    - HUMHUB_VERSION=develop

matrix:
  allow_failures:
    - env: HUMHUB_VERSION=develop
  fast_finish: true


cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - chmod +x .travis/*.sh

install:
  - .travis/install-dependencies.sh
  - .travis/setup-humhub.sh

before_script:
  - $HOME/chromedriver --url-base=/wd/hub &
  - php --server 127.0.0.1:8080 --docroot ${HUMHUB_PATH} &>/dev/null &
  - sleep 5
  - curl --fail --head http://127.0.0.1:8080/index-test.php

script:
  - cd tests
  - ln -s ${HUMHUB_PATH}/protected/humhub/tests/config/env config/ # create symlink from /opt/humhub to config/
  - sed -i -e "s|../../../humhub/tests/config/env|config/env|g" codeception.yml # fix relative path for codeception
  - php ${HUMHUB_PATH}/protected/vendor/bin/codecept build
  - php ${HUMHUB_PATH}/protected/vendor/bin/codecept run --env travis
